apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
spec:
  rules:
    - host: jenkins.jbgroup.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .values.loadbalancer }}
                port:
                  number: 80